# Generated by Django 6.0.3 on 2026-04-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_or_territory', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('metric', models.CharField(max_length=150)),
                ('value', models.FloatField()),
            ],
        ),
    ]
